/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.com.interfaz;

import java.awt.Color;

/**
 *
 * @author DELL
 */
public class actualizar extends javax.swing.JPanel {

    /**
     * Creates new form actualizar
     */
    public actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloinsertar = new javax.swing.JLabel();
        subtituloNombre = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        subtituloNombre1 = new javax.swing.JLabel();
        nombretxt1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        nombretxt2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        subtituloNombre2 = new javax.swing.JLabel();
        subtituloNombre3 = new javax.swing.JLabel();
        Dulce = new javax.swing.JCheckBox();
        Dulce1 = new javax.swing.JCheckBox();
        Dulce2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 47, 137));

        tituloinsertar.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        tituloinsertar.setForeground(new java.awt.Color(255, 255, 255));
        tituloinsertar.setText("Actualizar dulces");

        subtituloNombre.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloNombre.setForeground(new java.awt.Color(255, 255, 255));
        subtituloNombre.setText("Nombre");

        nombretxt.setBackground(new java.awt.Color(176, 47, 137));
        nombretxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(153, 153, 153));
        nombretxt.setText("Ingrese el nombre del dulce");
        nombretxt.setBorder(null);
        nombretxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombretxtMousePressed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        subtituloNombre1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloNombre1.setForeground(new java.awt.Color(255, 255, 255));
        subtituloNombre1.setText("Precio");

        nombretxt1.setBackground(new java.awt.Color(176, 47, 137));
        nombretxt1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        nombretxt1.setForeground(new java.awt.Color(153, 153, 153));
        nombretxt1.setText("Ingrese el precio del dulce");
        nombretxt1.setBorder(null);
        nombretxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombretxt1MousePressed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        nombretxt2.setBackground(new java.awt.Color(176, 47, 137));
        nombretxt2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        nombretxt2.setForeground(new java.awt.Color(153, 153, 153));
        nombretxt2.setText("Ingrese la descripcion del dulce");
        nombretxt2.setBorder(null);
        nombretxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombretxt2MousePressed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        subtituloNombre2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloNombre2.setForeground(new java.awt.Color(255, 255, 255));
        subtituloNombre2.setText("Descripcion");

        subtituloNombre3.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloNombre3.setForeground(new java.awt.Color(255, 255, 255));
        subtituloNombre3.setText("Categoria");

        Dulce.setText("Dulce");
        Dulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DulceActionPerformed(evt);
            }
        });

        Dulce1.setText("Acido");
        Dulce1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dulce1ActionPerformed(evt);
            }
        });

        Dulce2.setText("Sin azucar");
        Dulce2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dulce2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setText("Guardar datos");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtituloNombre3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtituloNombre)
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtituloNombre2)
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombretxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Dulce)
                                            .addComponent(Dulce2)
                                            .addComponent(Dulce1)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(subtituloNombre1)
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nombretxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(79, 79, 79))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(tituloinsertar)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tituloinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtituloNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtituloNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombretxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtituloNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombretxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(subtituloNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Dulce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dulce1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dulce2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void nombretxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombretxtMousePressed
        if (nombretxt.getText().equals("Ingrese el nombre del dulce")){
            nombretxt.setText("");
            nombretxt.setForeground(Color.black);
        }

    }//GEN-LAST:event_nombretxtMousePressed

    private void nombretxt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombretxt1MousePressed
        if (nombretxt1.getText().equals("Ingrese el precio del dulce")){
            nombretxt1.setText("");
            nombretxt1.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_nombretxt1MousePressed

    private void nombretxt2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombretxt2MousePressed
        if (nombretxt2.getText().equals("Ingrese la descripcion del dulce")){
            nombretxt2.setText("");
            nombretxt2.setForeground(Color.black);
        }
    }//GEN-LAST:event_nombretxt2MousePressed

    private void DulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DulceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DulceActionPerformed

    private void Dulce1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dulce1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dulce1ActionPerformed

    private void Dulce2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dulce2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dulce2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Dulce;
    private javax.swing.JCheckBox Dulce1;
    private javax.swing.JCheckBox Dulce2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTextField nombretxt1;
    private javax.swing.JTextField nombretxt2;
    private javax.swing.JLabel subtituloNombre;
    private javax.swing.JLabel subtituloNombre1;
    private javax.swing.JLabel subtituloNombre2;
    private javax.swing.JLabel subtituloNombre3;
    private javax.swing.JLabel tituloinsertar;
    // End of variables declaration//GEN-END:variables
}
