/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.com.interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author DELL
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    int xMouse,yMouse;
    public interfaz() {
        initComponents();
        
        
        this.setLocationRelativeTo(this);
        SetImageLabel(Logo,"src/com/images/logo.jpeg");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelDerecho = new javax.swing.JPanel();
        TextoBienvenido = new javax.swing.JLabel();
        TextoDigiteOpcion = new javax.swing.JLabel();
        Panelinsertar = new javax.swing.JPanel();
        TextoInsertar = new javax.swing.JLabel();
        PanelActualizar = new javax.swing.JPanel();
        TextoActualizar = new javax.swing.JLabel();
        PanelEliminar = new javax.swing.JPanel();
        TextoEliminar = new javax.swing.JLabel();
        PanelBuscar = new javax.swing.JPanel();
        TextoBuscar = new javax.swing.JLabel();
        PanelAcercade = new javax.swing.JPanel();
        TextoAcercade = new javax.swing.JLabel();
        PanelListar = new javax.swing.JPanel();
        TextoListar = new javax.swing.JLabel();
        Ventana = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tu dulceria de confianza");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, 30));

        PanelDerecho.setBackground(new java.awt.Color(51, 0, 51));

        TextoBienvenido.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        TextoBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        TextoBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoBienvenido.setText("Bienvenido");

        TextoDigiteOpcion.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        TextoDigiteOpcion.setForeground(new java.awt.Color(255, 255, 255));
        TextoDigiteOpcion.setText("Digite la opción a realizar");

        Panelinsertar.setBackground(new java.awt.Color(134, 36, 115));
        Panelinsertar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Panelinsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelinsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelinsertarMouseExited(evt);
            }
        });

        TextoInsertar.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        TextoInsertar.setForeground(new java.awt.Color(255, 255, 255));
        TextoInsertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoInsertar.setText("Insertar dulce");
        TextoInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoInsertarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoInsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoInsertarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelinsertarLayout = new javax.swing.GroupLayout(Panelinsertar);
        Panelinsertar.setLayout(PanelinsertarLayout);
        PanelinsertarLayout.setHorizontalGroup(
            PanelinsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelinsertarLayout.setVerticalGroup(
            PanelinsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        PanelActualizar.setBackground(new java.awt.Color(134, 36, 115));
        PanelActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        TextoActualizar.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        TextoActualizar.setForeground(new java.awt.Color(255, 255, 255));
        TextoActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoActualizar.setText("Actualizar dulce");
        TextoActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoActualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoActualizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelActualizarLayout = new javax.swing.GroupLayout(PanelActualizar);
        PanelActualizar.setLayout(PanelActualizarLayout);
        PanelActualizarLayout.setHorizontalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelActualizarLayout.setVerticalGroup(
            PanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        PanelEliminar.setBackground(new java.awt.Color(134, 36, 115));
        PanelEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        TextoEliminar.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        TextoEliminar.setForeground(new java.awt.Color(255, 255, 255));
        TextoEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoEliminar.setText("Eliminar dulce");
        TextoEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelEliminarLayout = new javax.swing.GroupLayout(PanelEliminar);
        PanelEliminar.setLayout(PanelEliminarLayout);
        PanelEliminarLayout.setHorizontalGroup(
            PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelEliminarLayout.setVerticalGroup(
            PanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        PanelBuscar.setBackground(new java.awt.Color(134, 36, 115));
        PanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        TextoBuscar.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        TextoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        TextoBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoBuscar.setText("Buscar dulce");
        TextoBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
        PanelBuscar.setLayout(PanelBuscarLayout);
        PanelBuscarLayout.setHorizontalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBuscarLayout.setVerticalGroup(
            PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        PanelAcercade.setBackground(new java.awt.Color(134, 36, 115));
        PanelAcercade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        TextoAcercade.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        TextoAcercade.setForeground(new java.awt.Color(255, 255, 255));
        TextoAcercade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoAcercade.setText("Acerca de");
        TextoAcercade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoAcercade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoAcercadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoAcercadeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelAcercadeLayout = new javax.swing.GroupLayout(PanelAcercade);
        PanelAcercade.setLayout(PanelAcercadeLayout);
        PanelAcercadeLayout.setHorizontalGroup(
            PanelAcercadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoAcercade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelAcercadeLayout.setVerticalGroup(
            PanelAcercadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoAcercade, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        PanelListar.setBackground(new java.awt.Color(134, 36, 115));
        PanelListar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        TextoListar.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        TextoListar.setForeground(new java.awt.Color(255, 255, 255));
        TextoListar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoListar.setText("Listar dulces");
        TextoListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextoListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextoListarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextoListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextoListarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelListarLayout = new javax.swing.GroupLayout(PanelListar);
        PanelListar.setLayout(PanelListarLayout);
        PanelListarLayout.setHorizontalGroup(
            PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelListarLayout.setVerticalGroup(
            PanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextoListar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelDerechoLayout = new javax.swing.GroupLayout(PanelDerecho);
        PanelDerecho.setLayout(PanelDerechoLayout);
        PanelDerechoLayout.setHorizontalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechoLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelAcercade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panelinsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextoDigiteOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelListar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
            .addComponent(TextoBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelDerechoLayout.setVerticalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerechoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TextoBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoDigiteOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panelinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(PanelListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelAcercade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        bg.add(PanelDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 270, 510));

        Ventana.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout VentanaLayout = new javax.swing.GroupLayout(Ventana);
        Ventana.setLayout(VentanaLayout);
        VentanaLayout.setHorizontalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        VentanaLayout.setVerticalGroup(
            VentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        bg.add(Ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoInsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoInsertarMouseEntered
        Panelinsertar.setBackground(new Color(197,54,168));
    }//GEN-LAST:event_TextoInsertarMouseEntered

    private void TextoInsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoInsertarMouseExited
        Panelinsertar.setBackground(new Color(134,36,115));
    }//GEN-LAST:event_TextoInsertarMouseExited

    private void PanelinsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelinsertarMouseEntered
        //Panelinsertar.setBackground(new Color(197,54,168));
    }//GEN-LAST:event_PanelinsertarMouseEntered

    private void PanelinsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelinsertarMouseExited
        //Panelinsertar.setBackground(new Color(134,36,115));
    }//GEN-LAST:event_PanelinsertarMouseExited

    private void TextoActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoActualizarMouseEntered
        PanelActualizar.setBackground(new Color(197,54,168));
    }//GEN-LAST:event_TextoActualizarMouseEntered

    private void TextoActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoActualizarMouseExited
        PanelActualizar.setBackground(new Color(134,36,115));
    }//GEN-LAST:event_TextoActualizarMouseExited

    private void TextoEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoEliminarMouseEntered
        PanelEliminar.setBackground(new Color(197,54,168));
    }//GEN-LAST:event_TextoEliminarMouseEntered

    private void TextoEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoEliminarMouseExited
        PanelEliminar.setBackground(new Color(134,36,115));
    }//GEN-LAST:event_TextoEliminarMouseExited

    private void TextoBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoBuscarMouseEntered
        PanelBuscar.setBackground(new Color(197,54,168));
    }//GEN-LAST:event_TextoBuscarMouseEntered

    private void TextoBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoBuscarMouseExited
        PanelBuscar.setBackground(new Color(134,36,115));
    }//GEN-LAST:event_TextoBuscarMouseExited

    private void TextoListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoListarMouseEntered
        PanelListar.setBackground(new Color(197,54,168));
    }//GEN-LAST:event_TextoListarMouseEntered

    private void TextoListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoListarMouseExited
        PanelListar.setBackground(new Color(134,36,115));
    }//GEN-LAST:event_TextoListarMouseExited

    private void TextoAcercadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoAcercadeMouseEntered
        PanelAcercade.setBackground(new Color(197,54,168));
    }//GEN-LAST:event_TextoAcercadeMouseEntered

    private void TextoAcercadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoAcercadeMouseExited
        PanelAcercade.setBackground(new Color(134,36,115));
    }//GEN-LAST:event_TextoAcercadeMouseExited

    private void TextoInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoInsertarMouseClicked
        insertar i2 = new insertar();
        i2.setSize(530,510);
        i2.setLocation(0,0);
        
        Ventana.removeAll();
        Ventana.add(i2,BorderLayout.CENTER);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_TextoInsertarMouseClicked

    private void TextoActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoActualizarMouseClicked
        actualizar i3 = new actualizar();
        i3.setSize(530,510);
        i3.setLocation(0,0);
        
        Ventana.removeAll();
        Ventana.add(i3,BorderLayout.CENTER);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_TextoActualizarMouseClicked

    private void TextoEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoEliminarMouseClicked
        eliminar i4 = new eliminar();
        i4.setSize(530,510);
        i4.setLocation(0,0);
        
        Ventana.removeAll();
        Ventana.add(i4,BorderLayout.CENTER);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_TextoEliminarMouseClicked

    private void TextoBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoBuscarMouseClicked
        Buscar i5 = new Buscar();
        i5.setSize(530,510);
        i5.setLocation(0,0);
        
        Ventana.removeAll();
        Ventana.add(i5,BorderLayout.CENTER);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_TextoBuscarMouseClicked

    private void TextoListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoListarMouseClicked
        listar i6 = new listar();
        i6.setSize(530,510);
        i6.setLocation(0,0);
        
        Ventana.removeAll();
        Ventana.add(i6,BorderLayout.CENTER);
        Ventana.revalidate();
        Ventana.repaint();
    }//GEN-LAST:event_TextoListarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }
    
    private void SetImageLabel(JLabel labelName,String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(),labelName.getHeight(),Image.SCALE_DEFAULT));
                labelName.setIcon(icon);
                this.repaint();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelAcercade;
    private javax.swing.JPanel PanelActualizar;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelDerecho;
    private javax.swing.JPanel PanelEliminar;
    private javax.swing.JPanel PanelListar;
    private javax.swing.JPanel Panelinsertar;
    private javax.swing.JLabel TextoAcercade;
    private javax.swing.JLabel TextoActualizar;
    private javax.swing.JLabel TextoBienvenido;
    private javax.swing.JLabel TextoBuscar;
    private javax.swing.JLabel TextoDigiteOpcion;
    private javax.swing.JLabel TextoEliminar;
    private javax.swing.JLabel TextoInsertar;
    private javax.swing.JLabel TextoListar;
    private javax.swing.JPanel Ventana;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
