/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.components;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.Color;

import javax.swing.JOptionPane;

import controller.DulceriaController;
import models.Categorias;
import models.Dulce;
/**
 *
 * @author DELL
 */
public class actualizar extends javax.swing.JPanel {

    /**
     * Creates new form actualizar
     */
    private DulceriaController controller;
    
    public actualizar(DulceriaController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        nombretxt = new javax.swing.JTextField();
        subtituloNombre = new javax.swing.JLabel();
        tituloinsertar = new javax.swing.JLabel();
        subtituloNombre1 = new javax.swing.JLabel();
        CBNombre = new javax.swing.JCheckBox();
        CBDescripcion = new javax.swing.JCheckBox();
        CBPrecio = new javax.swing.JCheckBox();
        CBCategoria = new javax.swing.JCheckBox();
        change = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 47, 137));

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setText("Buscar dulce");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        nombretxt.setBackground(new java.awt.Color(176, 47, 137));
        nombretxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        nombretxt.setForeground(new java.awt.Color(153, 153, 153));
        nombretxt.setText("Ingrese el nombre del dulce");
        nombretxt.setBorder(null);
        nombretxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombretxtMousePressed(evt);
            }
        });

        subtituloNombre.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloNombre.setForeground(new java.awt.Color(255, 255, 255));
        subtituloNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtituloNombre.setText("¿Que desea modificar?");

        tituloinsertar.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        tituloinsertar.setForeground(new java.awt.Color(255, 255, 255));
        tituloinsertar.setText("Actualizar dulces");

        subtituloNombre1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        subtituloNombre1.setForeground(new java.awt.Color(255, 255, 255));
        subtituloNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtituloNombre1.setText("Modificar dulce");

        CBNombre.setText("Nombre");
        CBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNombreActionPerformed(evt);
            }
        });

        CBDescripcion.setText("Descripcion");
        CBDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDescripcionActionPerformed(evt);
            }
        });


        CBPrecio.setText("Precio");
        CBPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPrecioActionPerformed(evt);
            }
        });

        CBCategoria.setText("Categoria (Dulce,Acido,Sin azucar)");
        CBCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCategoriaActionPerformed(evt);
            }
        });

        change.setText("");

        jButton3.setBackground(new java.awt.Color(153, 0, 153));
        jButton3.setText("Modificar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subtituloNombre)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBNombre)
                            .addComponent(CBDescripcion)
                            .addComponent(CBPrecio)
                            .addComponent(CBCategoria)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(tituloinsertar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(subtituloNombre1)
                    .addContainerGap(375, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tituloinsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(CBNombre)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBPrecio)
                    .addComponent(subtituloNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(subtituloNombre1)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 510));
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (nombretxt.getText().equals("Ingrese el nombre del dulce") || nombretxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingresa el nombre a buscar");
            return;
        }

        dulceResultado = controller.buscarPorNombre(nombretxt.getText());
        if(dulceResultado != null){
            JOptionPane.showMessageDialog(this,"Dulce encontrado");
            return;
        }else{
            JOptionPane.showMessageDialog(this,"No se encontro el dulce: "+nombretxt.getText());
            return;
        }
    }                                        

    private void nombretxtMousePressed(java.awt.event.MouseEvent evt) {                                       
        if (nombretxt.getText().equals("Ingrese el nombre del dulce")){
            nombretxt.setText("");
            nombretxt.setForeground(Color.black);
        }
    }                                      

    private void CBNombreActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CBCategoria.setSelected(false);
        CBNombre.setSelected(true);
        CBPrecio.setSelected(false);
        CBDescripcion.setSelected(false);    
    }                                        

    private void CBPrecioActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CBCategoria.setSelected(false);
        CBNombre.setSelected(false);
        CBPrecio.setSelected(true);
        CBDescripcion.setSelected(false);
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
        if(CBNombre.isSelected() != false){
            dulceResultado.setNombre(change.getText());
        }
        if(CBPrecio.isSelected() != false){
            dulceResultado.setPrecio(Integer.parseInt(change.getText()));
        }
        if(CBDescripcion.isSelected() != false){
            dulceResultado.setDescripcion(change.getText());
        }
        if(CBCategoria.isSelected() != false){
            if(change.getText().toUpperCase().equals("ACIDO")){
                categoriaSelect = "ACIDO";    
            }
            if(change.getText().toUpperCase().equals("SIN AZUCAR")){
                categoriaSelect = "SINAZUCAR";    
            }
            if(change.getText().toUpperCase().equals("DULCE")){
                categoriaSelect = "DULCE";    
            }

            Categorias categoria = Categorias.valueOf(categoriaSelect);
            dulceResultado.setCategoria(categoria);
        }
        
        JOptionPane.showMessageDialog(this,"Dulce modificado");
        nombretxt.setText("");
        change.setText("");
        CBCategoria.setSelected(false);
        CBNombre.setSelected(false);
        CBPrecio.setSelected(false);
        CBDescripcion.setSelected(false);                                        
    
    }                                        

    private void CBCategoriaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CBCategoria.setSelected(true);
        CBNombre.setSelected(false);
        CBPrecio.setSelected(false);
        CBDescripcion.setSelected(false);
    }                                           

    private void CBDescripcionActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CBCategoria.setSelected(false);
        CBNombre.setSelected(false);
        CBPrecio.setSelected(false);
        CBDescripcion.setSelected(true);
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox CBCategoria;
    private javax.swing.JCheckBox CBDescripcion;
    private javax.swing.JCheckBox CBNombre;
    private javax.swing.JCheckBox CBPrecio;
    private javax.swing.JTextField change;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JLabel subtituloNombre;
    private javax.swing.JLabel subtituloNombre1;
    private javax.swing.JLabel tituloinsertar;
    private String categoriaSelect;
    private Dulce dulceResultado;
    // End of variables declaration                   
}